# Continuous integration to Docker Hub, with selectable auditing.
name: BuildLax

on:
  workflow_dispatch:
    inputs:
      run_lint:
        description: 'Lint with RuboCop?'
        required: true
        type: boolean
        default: false
      run_brakeman:
        description: 'Audit app with Brakeman?'
        required: true
        type: boolean
        default: true
      run_bundle_audit:
        description: 'Audit dependencies with bundle-audit?'
        required: true
        type: boolean
        default: false
  workflow_call:
    inputs:
      run_lint:
        description: 'Lint with RuboCop?'
        required: false
        type: boolean
        default: false
      run_brakeman:
        description: 'Audit app with Brakeman?'
        required: false
        type: boolean
        default: true
      run_bundle_audit:
        description: 'Audit dependencies with bundle-audit?'
        required: false
        type: boolean
        default: false

jobs:
  audit:
    name: Selective Audit
    uses: ./.github/workflows/rubyonrails-lint.yml
    with:
      # Only run each audit if the user has specified to do so.
      skip-lint: ${{ ! inputs.run_lint }}
      skip-deps-audit: ${{ ! inputs.run_bundle_audit }}
      skip-app-audit: ${{ ! inputs.run_brakeman }}
