# Extract metadata, ruby version, build and push to Docker Hub
# called from ci_caller.yml
name: Build and push

on:
  workflow_call:
    inputs:
      image:
        description: 'Image name to push'
        required: true
        type: string
#    secrets: inherit

jobs:
  docker:
    name: 'Extract metadata, Build and push to Docker Hub'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Ruby version
        id: ruby
        run: |
          echo "ruby-version=`cat .ruby-version`" >> $GITHUB_OUTPUT
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            RUBY_VERSION=${{ steps.ruby.outputs.ruby-version }}
