# Continuous integration to Docker Hub, without auditing.
name: BuildLax

on:
  push:
    branches:
      - 'rails-6'
  pull_request:
    branches:
      - 'rails-6'

jobs:
  audit:
    name: AuditABit
    uses: ./.github/workflows/rubyonrails-lint.yml
    with:
      # Rubocop is disabled currently, until the rest of the code has been rubocopped.
      skip-lint: true
      # There is no point auditing something that has known other dependency audit failures
      skip-deps-audit: true

  tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml

  docker:
    name: 'Extract metadata, Build and push to Docker Hub'
    runs-on: ubuntu-latest
    needs: [ audit, tests ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: jmessenger/maint-autobuild-lax
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get Ruby version
        id: ruby
        run: echo "::set-output name=ruby-version::`cat .ruby-version`"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            RUBY_VERSION=${{ steps.ruby.outputs.ruby-version }}
