# Continuous integration to Docker Hub
name: Build with selective audit
on:
  push:
    branches:
      - 'master'
      - 'rails-6'
  pull_request:
    branches:
      - 'master'
      - 'rails-6'
    tags:
      - '[vt]*'

jobs:
  image_name:
    name: Parse reference to determine image name
    runs-on: ubuntu-latest
    steps:
      - name: Print reference
        run: |
          echo "::notice::Ref_name: ${{ github.ref_name }}"
      - name: Choose master image
        if: ${{ github.ref_name == "master" || ( github.ref_type == "tag" && startsWith(github.ref_name, "v") }}
        run: |
          echo "image=$Image" >> $GITHUB_OUTPUTS
          echo "::notice::Image name: $Image"
        env:
          Image: jmessenger/maint-autobuild
      - name: Choose test image
        if: ${{ github.ref_name != "master" || ( github.ref_type == "tag" && startsWith(github.ref_name, "t") }}
        run: |
          echo "image=$Image" >> $GITHUB_OUTPUTS
          echo "::notice::Image name: $Image"
        env:
          Image: jmessenger/maint-autobuild-lax
      - name: abort
        run: |
          echo "::notice::Chose: ${{jobs.image_name.outputs.image}}"
          exit 1

  audit:
    name: Run selective audit
    uses: ./.github/workflows/audit-lax.yml
    with:
      run-bundle-audit: false
      run-lint: false
      run-brakeman: true

  tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml

  build:
    name: Build and push
    needs: [ audit, tests, image_name ]
    uses: ./.github/workflows/build.yml
    with:
      image: jmessenger/maint-autobuild-lax
    secrets: inherit
