# Continuous integration to Docker Hub
name: Build with selective audit
on:
  push:
    branches:
      - 'rails-6'
  pull_request:
    branches:
      - 'rails-6'

jobs:
  audit:
    name: Run selective audit
    uses: ./.github/workflows/audit-lax.yml
    with:
      run-bundle-audit: false
      run-lint: false
      run-brakeman: true

  tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml

  build:
    name: Build and push
    needs: [ audit, tests ]
    uses: ./.github/workflows/build.yml
    with:
      image: jmessenger/maint-autobuild-lax
    secrets: inherit
