name: Dockerhub ci

on:
  push:
    branches:
      - 'master'
    tags:
      - 't*'
  pull_request:
    branches:
      - 'master'

jobs:
  audit:
    name: Audit
    uses: ./.github/workflows/rubyonrails-lint.yml
    with:
      skip-lint: true

  docker:
    runs-on: ubuntu-latest
    needs: audit
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: jmessenger/maint-autobuild
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get Ruby version
        id: ruby
        run: echo "::set-output name=ruby-version::`cat .ruby-version`"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            RUBY_VERSION=${{ steps.ruby.outputs.ruby-version }}
