# Continuous integration to Docker Hub
on:
  push:
    branches:
      - 'rails-6'
  pull_request:
    branches:
      - 'rails-6'

jobs:
  audit:
    name: Run selective audit
    uses: ./.github/workflows/audit-lax.yml
    with:
      run_bundle_audit: true

  tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml

  docker:
    name: 'Extract metadata, Build and push to Docker Hub'
    runs-on: ubuntu-latest
    needs: [ audit, tests ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Ruby version
        id: ruby
        run: |
          echo "ruby-version=`cat .ruby-version`" >> $GITHUB_OUTPUT
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jmessenger/maint-autobuild-lax
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            RUBY_VERSION=${{ steps.ruby.outputs.ruby-version }}
