# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Run tests with rake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['.ruby-version' ]
        postgres-version: [ '13', 'latest' ]
    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # It uses v1 as a code for "The latest version with automatic fixes etc.", referred to as a floating V1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Set up database schema
      run: bin/rails db:setup
      env:
        SERVER_PRODUCTION: www.nothing.fish
        SERVER_STAGING: www.nothing.fish
        SERVER_DEVELOPMENT: www.nothing.fish
        HOST_PORT: 80
        COMMITTEE: 12.5
        REQ_URL: https://www.nothing.fish/items/%s
        MAIL_SENDER: admin@nothingfish.org

    - name: Run tests
      run: bundle exec rake
      env:
        SERVER_PRODUCTION: www.nothing.fish
        SERVER_STAGING: www.nothing.fish
        SERVER_DEVELOPMENT: www.nothing.fish
        HOST_PORT: 80
        COMMITTEE: 12.5
        REQ_URL: https://www.nothing.fish/items/%s
        MAIL_SENDER: admin@nothingfish.org
