# Continuous integration to Docker Hub
name: Build test images with selective audit
on:
  push:
    branches:
      - 'rails-6'
    tags:
      - '[t]*'
  pull_request:
    branches:
      - 'rails-6'

jobs:
  audit:
    name: Run selective audit
    uses: ./.github/workflows/selective-audit.yml
    with:
      run-bundle-audit: false
      run-lint: false
      run-brakeman: true

  tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml

  build:
    name: Build and push
    needs: [ audit, tests, image_name ]
    uses: ./.github/workflows/build.yml
    with:
      image: jmessenger/maint-autobuild-test
    secrets: inherit
